python3 ocr-data.py dataset/1 &&
python3 ocr-data.py dataset/2 &&
python3 ocr-data.py dataset/3 &&
python3 ocr-data.py dataset/4 &&
python3 ocr-data.py dataset/5 &&
python3 ocr-data.py dataset/6 &&
python3 ocr-data.py dataset/7 &&
python3 ocr-data.py dataset/8 &&
python3 ocr-data.py dataset/9 &&
python3 ocr-data.py dataset/10 &&
python3 ocr-data.py dataset/11 &&
python3 ocr-data.py dataset/12 &&
python3 ocr-data.py dataset/13 &&
python3 ocr-data.py dataset/14 &&
python3 ocr-data.py dataset/15 &&
python3 ocr-data.py dataset/16 &&
python3 ocr-data.py dataset/17 &&
python3 ocr-data.py dataset/18 &&
python3 ocr-data.py dataset/19 &&
python3 ocr-data.py dataset/20 &&
python3 ocr-data.py dataset/21 &&
python3 ocr-data.py dataset/22 &&
python3 ocr-data.py dataset/23
